swadesh_words = [
    "I",
    "you",
    "he",
    "we",
    "you",
    "they",
    "this",
    "that",
    "here",
    "there",
    "who",
    "what",
    "where",
    "when",
    "how",
    "not",
    "all",
    "many",
    "some",
    "few",
    "other",
    "one",
    "two",
    "three",
    "four",
    "five",
    "big",
    "long",
    "wide",
    "thick",
    "heavy",
    "small",
    "short",
    "narrow",
    "thin",
    "woman",
    "man",
    "child",
    "wife",
    "husband",
    "mother",
    "father",
    "animal",
    "fish",
    "bird",
    "dog",
    "louse",
    "snake",
    "worm",
    "tree",
    "forest",
    "stick",
    "fruit",
    "seed",
    "leaf",
    "root",
    "bark",
    "flower",
    "grass",
    "rope",
    "skin",
    "meat",
    "blood",
    "bone",
    "fat",
    "egg",
    "horn",
    "tail",
    "feather",
    "hair",
    "head",
    "ear",
    "eye",
    "nose",
    "mouth",
    "tooth",
    "tongue",
    "fingernail",
    "foot",
    "leg",
    "knee",
    "hand",
    "wing",
    "belly",
    "guts",
    "neck",
    "back",
    "breast",
    "heart",
    "liver",
    "to drink",
    "to eat",
    "to bite",
    "to suck",
    "to spit",
    "to vomit",
    "to blow",
    "to breathe",
    "to laugh",
    "to see",
    "to hear",
    "to know",
    "to think",
    "to smell",
    "to fear",
    "to sleep",
    "to live",
    "to die",
    "to kill",
    "to fight",
    "to hunt",
    "to hit",
    "to cut",
    "to split",
    "to stab",
    "to scratch",
    "to dig",
    "to swim",
    "to fly",
    "to walk",
    "to come",
    "to lie",
    "to sit",
    "to stand",
    "to turn",
    "to fall",
    "to give",
    "to hold",
    "to squeeze",
    "to rub",
    "to wash",
    "to wipe",
    "to pull",
    "to push",
    "to throw",
    "to tie",
    "to sew",
    "to count",
    "to say",
    "to sing",
    "to play",
    "to float",
    "to flow",
    "to freeze",
    "to swell",
    "sun",
    "moon",
    "star",
    "water",
    "rain",
    "river",
    "lake",
    "sea",
    "salt",
    "stone",
    "sand",
    "dust",
    "earth",
    "cloud",
    "fog",
    "sky",
    "wind",
    "snow",
    "ice",
    "smoke",
    "fire",
    "ash",
    "to burn",
    "road",
    "mountain",
    "red",
    "green",
    "yellow",
    "white",
    "black",
    "night",
    "day",
    "year",
    "warm",
    "cold",
    "full",
    "new",
    "old",
    "good",
    "bad",
    "rotten",
    "dirty",
    "straight",
    "round",
    "sharp",
    "dull",
    "smooth",
    "wet",
    "dry",
    "correct",
    "near",
    "far",
    "right",
    "left",
    "at",
    "in",
    "with",
    "and",
    "if",
    "because",
    "name"
]
# removed specification of sense from the list

import sys
import click
sys.path.append('../')
from loader import JSONLTokenizedDataset
dataset = JSONLTokenizedDataset(root_path='../coca_tokenized_ettin_large', debug=False)

from transformers import AutoModelForMaskedLM, AutoTokenizer
# Load the saved model and tokenizer
#loadstr = '/home/ubuntu/bstadt-tlm/tlm/now-tlm-2025-08-15_15-08-29/checkpoint-112712/'
loadstr = '/home/bstadt/root/tlm/models/tlm-2025-08-05_16-42-11/checkpoint-10500/'
model = AutoModelForMaskedLM.from_pretrained(loadstr)
#tokenizer = BertTokenizerFast.from_pretrained('../coca_tokenized/tokenizer/')
tokenizer = AutoTokenizer.from_pretrained(loadstr)

from tqdm import tqdm
def mine_uses(phrase, tokenizer):
    uses = []
    for elem in tqdm(dataset):
        decoded = tokenizer.decode(elem['input_ids'])
        if phrase in decoded:
            uses.append(decoded)
    return uses


def main(phrase):
    """Mine uses of a target phrase from the dataset."""
    
    uses = mine_uses(phrase, tokenizer)
    
    # Create output filename based on the target phrase
    safe_phrase = phrase
    output_filename = f'{safe_phrase}_uses.txt'
    
    # Write the uses to a file
    print(f"Found {len(uses)} uses. Writing to {output_filename}")
    with open(output_filename, 'w') as f:
        for use in uses:
            f.write(use + '\n')
    
    print(f"Complete! Results saved to {output_filename}")

if __name__ == '__main__':
    for i, phrase in enumerate(swadesh_words):
        print(f"Processing {i+1} of {len(swadesh_words)}: {phrase}")
        main(phrase)
